# Generated by Django 3.0.5 on 2020-06-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbox',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='textbox',
            name='minutes',
        ),
    ]
