# Generated by Django 3.0.5 on 2020-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20200608_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbox',
            name='house',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textbox',
            name='interest',
            field=models.CharField(choices=[('gaming', 'gaming'), ('dancing', 'dancing'), ('singing', 'singing')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='textbox',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='textbox',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
