# Generated by Django 3.0.5 on 2020-06-14 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20200614_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('types', models.CharField(choices=[('gaming', 'gaming'), ('dancing', 'dancing'), ('singing', 'singing')], max_length=400, null=True)),
                ('deliver', models.ManyToManyField(to='todo_list.House')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_list.Textbox')),
            ],
        ),
    ]
