# Generated by Django 3.0.5 on 2020-06-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20200615_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deliver',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
