# Generated by Django 3.0.5 on 2020-06-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_linked_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='relbelongs',
            field=models.ManyToManyField(to='todo_list.Userinfo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='belongs',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
